# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_start = QtWidgets.QPushButton(self.centralwidget)
        self.Button_start.setGeometry(QtCore.QRect(690, 500, 75, 23))
        self.Button_start.setObjectName("Button_start")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 500, 54, 12))
        self.label.setObjectName("label")
        self.lineEdit_tnum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tnum.setGeometry(QtCore.QRect(590, 500, 61, 20))
        self.lineEdit_tnum.setObjectName("lineEdit_tnum")
        self.groupBox_condition = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_condition.setGeometry(QtCore.QRect(240, 110, 211, 271))
        self.groupBox_condition.setObjectName("groupBox_condition")
        self.checkBox_kdj = QtWidgets.QCheckBox(self.groupBox_condition)
        self.checkBox_kdj.setGeometry(QtCore.QRect(20, 30, 41, 16))
        self.checkBox_kdj.setObjectName("checkBox_kdj")
        self.checkBox_boll = QtWidgets.QCheckBox(self.groupBox_condition)
        self.checkBox_boll.setGeometry(QtCore.QRect(20, 170, 41, 16))
        self.checkBox_boll.setObjectName("checkBox_boll")
        self.label_2 = QtWidgets.QLabel(self.groupBox_condition)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 21, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_k = QtWidgets.QLineEdit(self.groupBox_condition)
        self.lineEdit_k.setGeometry(QtCore.QRect(50, 70, 41, 20))
        self.lineEdit_k.setObjectName("lineEdit_k")
        self.label_3 = QtWidgets.QLabel(self.groupBox_condition)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 21, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_d = QtWidgets.QLineEdit(self.groupBox_condition)
        self.lineEdit_d.setGeometry(QtCore.QRect(50, 100, 41, 20))
        self.lineEdit_d.setObjectName("lineEdit_d")
        self.label_4 = QtWidgets.QLabel(self.groupBox_condition)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 21, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_j = QtWidgets.QLineEdit(self.groupBox_condition)
        self.lineEdit_j.setGeometry(QtCore.QRect(50, 130, 41, 20))
        self.lineEdit_j.setObjectName("lineEdit_j")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_condition)
        self.comboBox.setGeometry(QtCore.QRect(20, 200, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(540, 100, 171, 271))
        self.groupBox.setObjectName("groupBox")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setGeometry(QtCore.QRect(0, 10, 171, 231))
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(50, 240, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(260, 430, 471, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "测试版 v1.0"))
        self.Button_start.setText(_translate("MainWindow", "开始"))
        self.label.setText(_translate("MainWindow", "线程数"))
        self.groupBox_condition.setTitle(_translate("MainWindow", "筛选条件"))
        self.checkBox_kdj.setText(_translate("MainWindow", "kdj"))
        self.checkBox_boll.setText(_translate("MainWindow", "boll"))
        self.label_2.setText(_translate("MainWindow", "k"))
        self.label_3.setText(_translate("MainWindow", "d"))
        self.label_4.setText(_translate("MainWindow", "j"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton.setText(_translate("MainWindow", "分析"))
